### ISSUE TITLE
Install CLI: How to obtain OpenStack OpenRC file to authenticate against API

### ISSUE THREAD

**Issue by stefreak** [syseleven/syselevenstack-documentation#45]
Description is missing how to obtain openrc file to use openstack CLI

https://doc.syselevenstack.com/en/tutorials/openstack-cli/

**Comment by stefreak** [comment]
@dschwabeS11 can you do it?

**Comment by dschwabeS11** [comment]
Notes how to finish setting up the cli config will be added to the "Conclusion" of the manual.

**Comment by dschwabeS11** [comment]
https://github.com/syseleven/syselevenstack-documentation/pull/46

**Comment by dschwabeS11** [comment]
This has been solved, can be closed.
